first changes
pluwiq/online_superstore pull request #1
Opened 2024-08-02 18:20 UTC by pluwiq

2024-08-03 11:35 UTC, TsikhanauDzmitry requested changes
Не нашел файл со скриптом, который проверяет созданные item, а также делает их в БД, если каких-то не хватает

2024-08-03 11:35 UTC, TsikhanauDzmitry commented on board_game.rb
> +  def self.from_db(row:)
Что делает данный метод?

2024-08-03 11:35 UTC, TsikhanauDzmitry commented on book.rb
> +    @isbn = isbn
Есть ли проверка на уникальность `isbn`?

2024-08-03 11:35 UTC, TsikhanauDzmitry commented on csv_order_source.rb
> +    return orders_hash.values unless File.exist?(@file_path)
А что вернется в таком случае? у нас же hash пустой

2024-08-03 11:35 UTC, TsikhanauDzmitry commented on csv_order_source.rb
> +    CSV.open(@file_path, "a+") do |csv|
Двойные кавычки?

2024-08-03 11:35 UTC, TsikhanauDzmitry commented on csv_order_source.rb
> +    orders.reject! { |o| o.id == order.id }
Что делает метод `reject!`?

2024-08-03 11:35 UTC, TsikhanauDzmitry commented on csv_order_source.rb
> +      end
не нравится мне методы с `O(n^2)`

2024-08-03 11:35 UTC, TsikhanauDzmitry commented on customer.rb
> +  end
Я этот метод смог в 2 строчки написать

2024-08-03 11:35 UTC, TsikhanauDzmitry commented on customer_input.rb
> +  end
Не напоминает ли это тебе методы проверки, что писали в Home-Zoo? Думаю, что тут можно все объединить под один метод, а также сделать вспомогательный `hash`/`метод`

2024-08-03 11:35 UTC, TsikhanauDzmitry commented on db_connection.rb
> +  end
Что по строгим параметрам?

2024-08-03 11:35 UTC, TsikhanauDzmitry commented on db_connection.rb
> +  end
Эти методы выздывают сами себя? Или же как? Не понимаю немного

2024-08-03 11:35 UTC, TsikhanauDzmitry commented on db_loader.rb
> +    result = conn.exec("SELECT * FROM items")
Обрати внимание на `"`

2024-08-03 11:35 UTC, TsikhanauDzmitry commented on online_store.rb
> +  FILE_NAME = 'orders.csv'.freeze
Тут можно и в приват

2024-08-03 11:35 UTC, TsikhanauDzmitry commented on online_store.rb
> +      puts "#{index + 1}. #{item.name} - #{item.price} (#{item.class.name})"
У нас же есть `id`. Зачем индекс? Или тут порядковое?

2024-08-03 11:35 UTC, TsikhanauDzmitry commented on online_store.rb
> +    return unless row
Можно объединить?)

2024-08-03 11:35 UTC, TsikhanauDzmitry commented on online_store.rb
> +      item or (puts 'Invalid item number.'; next)
что такое `or` и зачем оно нужно?

2024-08-03 11:35 UTC, TsikhanauDzmitry commented on online_store.rb
> +      item or (puts 'Invalid item number.'; next)
И вообще опиши мне работу этой строчки пожалуйста

2024-08-03 11:35 UTC, TsikhanauDzmitry commented on order.rb
> +    end
Избавляемся от каскадности

2024-08-03 11:35 UTC, TsikhanauDzmitry commented on validation.rb
> +end
Пустая строчка в конце файла

2024-08-03 11:35 UTC, TsikhanauDzmitry commented on validation.rb
> +  end
если не влазит в одну строчку, то можно и блоком передавать

2024-08-03 11:35 UTC, TsikhanauDzmitry commented on postgre_sql_order_source.rb
> +    @conn = PG.connect(dbname: 'online_store', user: ENV['DB_USER'], password: ENV['DB_PASSWORD'])
?

2024-08-03 11:35 UTC, TsikhanauDzmitry commented on order_helpers.rb
> +    return unless customer
в одну строчку?

2024-08-03 13:44 UTC, pluwiq commented on board_game.rb
> +  def self.from_db(row:)
метод `self.from_db` является методом класса, который создает новый экземпляр класса на основе данных, извлеченных из строки БД и преобразует данные из строки в объект, используя значения из хэша для инициализации атрибутов объекта.

2024-08-03 14:18 UTC, pluwiq commented on csv_order_source.rb
> +    return orders_hash.values unless File.exist?(@file_path)
если файл не существует, строка `return orders_hash.values` вернет пустой массив.  Вызов метода `values` на пустом хэше возвращает пустой массив. 


```
return [] unless File.exist?(@file_path)

    orders_hash = {}
```
такая запись наверное будет более правильной. Если файл не существует, метод возвращает пустой массив до выполнения основной логики метода.

2024-08-03 14:26 UTC, pluwiq commented on csv_order_source.rb
> +    orders.reject! { |o| o.id == order.id }
метод `reject!`  используется для удаления элементов из массива, которые соответствуют определенному условию, заданному блоком. Этот метод изменяет исходный массив, в отличие от метода `reject`, который возвращает новый массив с отфильтрованными элементами и не изменяет исходный массив.

если хотя бы один элемент был удален, `reject!` возвращает измененный массив.
если ни один элемент не был удален, `reject!` возвращает `nil`.

2024-08-03 14:51 UTC, pluwiq commented on db_connection.rb
> +  end
методы `exec_params` и `exec` служат для выполнения SQL-запросов в базе данных PostgreSQL, используя библиотеку `pg` . Они являются обертками вокруг методов `exec_params` и `exec` библиотеки `pg` и предоставляют стандартный интерфейс для выполнения запросов.

`exec_params` предназначен для выполнения SQL-запросов с параметрами
`exec` предназначен для выполнения SQL-запросов без параметров

2024-08-03 15:10 UTC, pluwiq commented on online_store.rb
> +      puts "#{index + 1}. #{item.name} - #{item.price} (#{item.class.name})"
исправлю)

2024-08-03 15:17 UTC, pluwiq commented on online_store.rb
> +      item or (puts 'Invalid item number.'; next)
оператор `or` используется для проверки двух условий. Он возвращает `true` и выполняет следующий за ним код, если хотя бы одно из условий истинно. В контексте этой строки оператор `or` используется для выполнения действия (вывода сообщения и перехода к следующей итерации цикла) в случае, если условие ложно.

можно наверное заменить на 
```
 if item.nil?
      puts 'Invalid item ID.'
      next
    end
```

2024-08-03 21:58 UTC, TsikhanauDzmitry requested changes

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on book.rb
> +    raise 'ISBN must be unique' if existing_book && existing_book.id != @id
В Ruby есть очень интересная штука: `&.`

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on book.rb
> +  end
Может быть этот метод будет лучше возвращать провалидированное поле?

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on book.rb
> +    from_db(row:)
Нельзя `from_db(row: result.first)`?

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on book.rb
> +  end
Что делает этот блок?

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on csv_order_source.rb
> +    orders.reject! { |o| o.id == order.id }
_если ни один элемент не был удален,_ `reject!` _возвращает_ `nil`.

Точно? Если не был удален ни один из элементов, то может быть был возвращен исходный массив? Можешь мне найти этот момент в документации?

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on csv_order_source.rb
> +      end
Не думала как избегать двойных циклов?

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on customer_input.rb
> +  INPUT_PROMPTS = {
Может в приват?

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on book.rb
> +    result = conn.exec_params('SELECT * FROM items WHERE isbn = $1 LIMIT 1', [isbn])
Почему не использован твой же класс `DBConnection`?

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on book.rb
> +    conn = PG.connect(dbname: ENV.fetch('DB_NAME'), user: ENV.fetch('DB_USER'), password: ENV.fetch('DB_PASSWORD'))
Почему ранее было `ENV['DB_NAME']`, а сейчас `ENV.fetch('DB_NAME')`? В чем разница?

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on db_loader.rb
> +    result.each do |row|
Не нравится название переменной `result`. Давай везде поменяем на то, что хранится в этой переменной. В данном случае `customers_from_db`

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on db_validator.rb
> +  REQUIRED_ITEMS = [
Зачем это тут?

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on db_validator.rb
> +    @conn = PG.connect(dbname: ENV.fetch('DB_NAME'), user: ENV.fetch('DB_USER'), password: ENV.fetch('DB_PASSWORD'))
Почему не использован твой же класс `DBConnection`?

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on db_validator.rb
> +    @conn = PG.connect(dbname: ENV.fetch('DB_NAME'), user: ENV.fetch('DB_USER'), password: ENV.fetch('DB_PASSWORD'))
Зачем в целом это инициализировать в коде столько раз? У тебя же есть свой класс, который как и раз и создан для того, чтобы общаться с БД

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on db_validator.rb
> +db_validator.validate_items
?????????????????????????????????

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on online_store.rb
> +    row = @db_conn.conn.exec_params('SELECT * FROM items WHERE id = $1 LIMIT 1', [id]).first or return
не надо делать `or`

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on online_store.rb
> +      puts "Select an item ID to add to your order, or type 'done' to finish:"
`"`

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on online_store.rb
> +      item or (puts 'Invalid item ID.'; next)
?

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on online_store.rb
> +    order or (puts 'Order not found.'; return)
?

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on online_store.rb
> +    end
В одну строчку помещается же

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on order.rb
> +      end
в одну

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on order_helpers.rb
> +    customer = find_customer(store:) ? customer : (return)
??????

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on order_helpers.rb
> +    customer = find_customer(store:) ? customer : (return)
Почему так, а не `return unless (customer = find_customer(store:))`?

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on order_helpers.rb
> +    puts('Order ID not found for this customer.') && return unless order
Последний раз повторюсь: сначала return, а потом то, что хотим сделать. Не надо никаких `&&`

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on postgre_sql_order_source.rb
> +        order.add_item(item:, quantity: item_row['quantity'].to_i)
Может быть: `order.add_item(item: Item.from_db(row: item_data), quantity: item_row['quantity'].to_i)`?

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on postgre_sql_order_source.rb
> +    order.id = order_id
`order.id = result.first['id'].to_i`?

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on postgre_sql_order_source.rb
> +    end
Перепиши мне это в один запрос к БД. Сейчас я вижу `order.items.count` запросов. Это не круто

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on postgre_sql_order_source.rb
> +    end
В других местах тоже

2024-08-03 21:58 UTC, TsikhanauDzmitry commented on postgre_sql_order_source.rb
> +    end
Правильно ли я понимаю, что мы делаем:
1. Обновляем сумму ордера
2. Удаляем все его айтемы
3. Заново добавляем ему айтемы

Если я правильно понял, то это слишком не правильно... Мы должны только обновить список (удалять только лишнее). Лучше отдельный метод какой добавить, а не вот так делать

2024-08-03 22:06 UTC, TsikhanauDzmitry requested changes

2024-08-03 22:06 UTC, TsikhanauDzmitry commented on online_store.rb
> +  FILE_NAME = 'orders.csv'.freeze
@pluwiq а где приват?

2024-08-03 22:06 UTC, TsikhanauDzmitry commented on db_connection.rb
> +  end
Так что?

2024-08-03 22:06 UTC, TsikhanauDzmitry commented on online_store.rb
> +      item or (puts 'Invalid item number.'; next)
Так не будет работать?
```
next puts 'Invalid item ID.' if item.nil?
```

2024-08-05 08:08 UTC, pluwiq commented on book.rb
> +  end
блок `ensure` используется для гарантированного выполнения кода, даже если в предыдущем коде возникло исключение. В нашем случае, он гарантирует закрытие соединения с базой данных, независимо от того, произошла ли ошибка при выполнении запроса или нет.

2024-08-05 08:13 UTC, pluwiq commented on csv_order_source.rb
> +    orders.reject! { |o| o.id == order.id }
[](https://apidock.com/ruby/Array/reject!)

[](https://www.rubydoc.info/stdlib/core/Array:reject%21)

2024-08-05 08:15 UTC, pluwiq commented on csv_order_source.rb
> +    orders.reject! { |o| o.id == order.id }
https://www.rubydoc.info/stdlib/core/Array:reject%21

2024-08-05 09:09 UTC, pluwiq commented on book.rb
> +    conn = PG.connect(dbname: ENV.fetch('DB_NAME'), user: ENV.fetch('DB_USER'), password: ENV.fetch('DB_PASSWORD'))
`.fetch` выбрасывает исключение `KeyError`, если переменная окружения не установлена и используется, когда необходимо гарантированно получить значение переменной окружения, и если оно не установлено, это должно привести к ошибке, чтобы можно было быстро обнаружить и исправить проблему.

2024-08-06 08:14 UTC, TsikhanauDzmitry requested changes

2024-08-06 08:14 UTC, TsikhanauDzmitry commented on book.rb
> +    raise 'ISBN must be unique' if existing_book && existing_book.id != @id
@pluwiq  И?

2024-08-06 08:14 UTC, TsikhanauDzmitry commented on db_validator.rb
> +DBValidator.new.validate_items
Давай это вызывать в `main.rb` когда запускается программа

2024-08-06 08:14 UTC, TsikhanauDzmitry commented on online_store.rb
> +    @orders = []
Нельзя тут сразу `@orders = load_orders`?

2024-08-06 08:14 UTC, TsikhanauDzmitry commented on order.rb
> +    end
Отступы съехали

2024-08-06 08:14 UTC, TsikhanauDzmitry commented on order_item_operations.rb
> +    unless items_to_delete.empty?
Может в таком случае использовать какой-нибудь обратный метод для `empty?`? 
https://blog.appsignal.com/2018/09/11/differences-between-nil-empty-blank-and-present.html

2024-08-08 09:11 UTC, TsikhanauDzmitry approved these changes
looks good

2024-08-08 09:17 UTC, merged